---
format: 
  docx:
    reference-doc: word-styles-reference-SEO_Interference_report.docx
title: "Interference Investigation Report"
date: |
  `r format(Sys.Date(), '%B %Y')`
  \
  \
  \
subtitle: |+
  \
  \
  Gabriel Ruiz\
  \
  vs.\
  \
  Gross Wilkinson Ranch
  \
  \
author: |+
  Ground Water Division\
  Wyoming State Engineer's Office\
toc: true
toc-title: Table of Contents
toc-depth: 2
number-sections: true
eol: crlf
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

{{< pagebreak >}}

# Introduction

On June 15, 2022, the Wyoming State Engineer's Office (SEO) received a letter from Mr. Daniel B. Frank, a lawyer representing Mr. Gabriel Ruiz, requesting a formal Interference Investigation. The letter requested the SEO evaluate potential damage to the Sherard Well No. 6, Permit No. U.W. 5461 by the Bill Ward No. 2 Well, Permit No. U.W. 8539, and Enl. Bill Ward No. 2 Well, Permit No. U.W. 12665. This letter is included in Appendix A.\

The two wells referenced above are fully adjudicated groundwater production wells located adjacent to an approximately 10 acre gravel pit near LaGrange, Wyoming, in southern Goshen County. The gravel pit intersects the water table, causing the pit to fill partially or completely with groundwater depending on seasonal water levels and irrigation pumping. The gravel pit and wells are located in the LaGrange alluvial valley, situated in between Bear and Horse Creeks, in an area of relatively heavy irrigation utilizing both surface and ground water rights.

## Complaint

Mr. Ruiz contends that pumping from the Bill Ward No. 2 Well (and its enlargement) draws down the level of the water in the gravel pit excessively. Mr. Ruiz requested an interference investigation pursuant to Wyo. Stat. § 41-3-911(b).\

Mr. Ruiz also believes that his Sherard Well No. 6 water rights and the Gross-Wilkinson Ranch, LLC' Bill Ward No. 2 are from the same source of supply, being the LaGrange Aquifer, and requested correlation of the priorities of water rights from this supply into a single schedule pursuant to Wyo. Stat. § 41-3-916. Mr. Ruiz suggested that it may be appropriate for the state engineer to adopt by order any of the corrective controls specified in Wyo. Stat. § 41-3-915.

Upon initial review of records, SEO personnel established the following:

1.  Valid water rights appear to exist for each of the wells in question.

2.  The wells are screened in the LaGrange Aquifer alluvium. The Bill Ward No. 2 Well is 60 feet deep, and the Sherard Well No. 6 Well is 43 feet deep. Both wells are screened across the full saturated thickness of the alluvium at their respective locations.

3.  The priority date of the Sherard Well No. 6 (05/14/1970) is senior to the priority date of the Bill Ward No. 2 Well (03/17/1971).

4.  The Sherard No. 6 Well is permitted for irrigation and miscellaneous use. The remarks section of the permit states that the miscellaneous use is for fish culture and recreational purposes.

5.  The Bill Ward No. 2 Well is permitted for irrigation use. The remarks section of the permit states that the property owners (at the time) agreed that Permit No. U.W. 5461 (Sherard No. 6) would have first right to use of the water.\

## Authority

W.S. § 41-3-911 provides the statutory framework for interference. It provides an enforceable legal remedy for surface water or groundwater appropriators whose rights are impaired by an interfering appropriator. The statute is applicable only when the impairment arises between two ground water appropriators, or between a ground water and surface water appropriator.\

The statutes relating to interference are:\

    §41-3-911.  Authority to order interfering appropriator to cease withdrawals of water; hearing complaints by appropriators.

        a.  Whenever a well withdrawing water for beneficial purposes shall interfere unreasonably with an adequate well developed solely for domestic or stock uses as defined in W.S. 41-3-907, whether in a control area or not, the state engineer may, on complaint of the operator of the stock or domestic well, order the interfering appropriator to cease or reduce withdrawals of underground water, unless such appropriator shall furnish at his own expense, sufficient water at the former place of use to meet the need for domestic or stock use. In case of interference between two (2) wells utilizing water for stock or domestic use as defined in W.S. 41-3-07, the appropriation with the earliest priority shall have the better right. 

        b.  Any appropriator of either surface or underground water may file a written complaint alleging interference with his water right by a junior right. Complaints are to be filed with the state engineer and are to be accompanied by a fee of one hundred dollars ($100.00) to help defray costs of investigation. This section is not applicable to interference between two (2) surface water rights. Upon receiving the complaint and fee, the state engineer shall undertake an investigation to determine if the alleged interference does exist. Following the investigation, the state engineer shall issue a report to all interested parties stating his findings. The report may suggest various means of stopping, rectifying or ameliorating the interference or damage caused thereby. 

         c. Any interested appropriator who is dissatisfied with the results of the foregoing procedure may proceed under the applicable provisions of the Wyoming Administrative Procedure Act [§§-16-3-101 through 16-3-115]. If a hearing is to be held, it shall be held before the appropriate water division superintendent. The superintendent shall report to the board of control at its next meeting. The board shall issue its order to include findings of fact and conclusions of law.

    §41-3-916.  Priority of rights when 1 source of supply. Where underground waters in different aquifers are so interconnected as to constitute in fact one source of supply, or where underground waters and the waters of surface streams are so interconnected as to constitute in fact one source of supply, priorities of rights to the use of all such interconnected waters shall be correlated and such single schedule of priorities shall relate to the whole common water supply. The state engineer may by order adopt any of the corrective controls specified in W.S. § 41 3 915.

    §41-3-933.  Express conditions limiting rights of appropriator; additional conditions. It is an express condition of each underground water permit that the right of the appropriator does not include the right to have the water level or artesian pressure at the appropriator's point of diversion maintained at any level or pressure higher than that required for maximum beneficial use of the water in the source of supply. The state engineer may issue any permits subject to such conditions as he may find to be in the public interest.

    §41-3-102.  Preferred uses; defined; order of preference.

        (a)  Water rights are hereby defined as follows according to use: preferred uses shall include rights for domestic and transportation purposes, steam power plants, and industrial purposes; existing rights not preferred, may be condemned to supply water for such preferred uses in accordance with the provisions of the law relating to condemnation of property for public and semi public purposes except as hereinafter provided. 

        (b)  Preferred water uses shall have preference rights in the following order: 
            (i)     Water for drinking purposes for both man and beast; 
            (ii Water for municipal purposes; 
            (iii)   Water for the use of steam engines and for general railway use, water for culinary, laundry, bathing, refrigerating (including the manufacture of ice), for steam and hot water heating plants, and steam power plants; and 
            (iv)    Industrial purposes. 

        (c)  The use of water for irrigation shall be superior and preferred to any use where water turbines or impulse water wheels are installed for power purposes; provided, however, that the preferred use of steam power plants and industrial purposes herein granted shall not be construed to give the right of condemnation.

{{< pagebreak >}}

## Water Rights

Appendix B provides copies of the permit documentation for the Sherard No. 6 and Bill Ward No. 2 wells. Figure 1 illustrates the location of the wells and the gravel pit. Summaries for completion and permit information for the wells referenced in this report are included on Table 1. Additionally, detailed information regarding the construction is provided below.\

The Bill Ward No. 2 Well is located on the south edge of the gravel pit, near the gravel jetty that historically divided the pit into two halves. The well is 60 feet deep and is slotted between 4 and 60 feet below ground surface (ft bgs). It has "pea sized" gravel pack and a cement seal around the surface casing. According to the statement of completion, the pump is set at 54 ft bgs. The water right is permitted for 2275 GPM max flow rate, for irrigation use on 319.8 acres (Gross Wilkinson Ranch also owns an additional 152 acres irrigated under other water rights). SEO personnel (T Moloney, Ground Water Division) observed this well operating on 8/29/2022. The observed flow rate was 500 GPM.

The Sherard No. 6 Well is located on the southeast edge of the pit. There is a metal intake structure in the pit below the location of the well, which may be piped together with the well. The well itself is located outside the pit. The well is 43 feet deep. A perforated interval was not indicated on the statement of completion but 6" by 1/4" perforation size was indicated. Static water level was measured at 3 ft bgs at the time of completion, so the perforated interval is assumed to be 3 feet to the total depth of the well, 43 feet. The depth of the pump setting is 20 feet. The water right is permitted for 2000 GPM max flow rate, for irrigation use on 185 acres, and miscellaneous use (fish culture and recreation in the gravel pit). SEO personnel (T Moloney, Ground Water Division) observed this well operation for a brief period on 8/29/2022. The observed flow rate was 200 GPM.

{{< pagebreak >}}

# Geologic and Hydrogeologic Overview

The geology of the LaGrange area in southeastern Wyoming was described by Rapp and others (1957) in their report on the geology and ground-water resources of Goshen County, and by Borchert (1976) in a report on the geohydrology of the Albin and LaGrange areas. Annual precipitation in nearby Torrington, Wyoming is approximately 14 inches per year (Rapp et al. 1957, NOAA U.S. Climate Normals 1991-2020). Mean net evaporation estimated using the Kohler-Nordenson-Fox equation with a coefficient of 0.7 for free-water surface evaporation at Whalen Diversion Dam (approximately 50 miles northwest of LaGrange) is approximately 34.8 inches per year based on data collected from 1949 to 1991 (Curtis and Grimes 2004).\

## Stratigraphy

Geologic strata occurring in the vicinity of LaGrange include the Lance Formation of Late Cretaceous age, the Chadron and Brule Formations of the White River Group of Oligocene age, the Arikaree Formation of early Miocene age, the terrace deposits of Pleistocene age, and the alluvium of Pleistocene and Holocene age. Geologic maps and stratigraphic columns of the area were developed by Borchert (1976) and refined by Stafford and Loveland (2020).\

## Hydrogeology

The Lance, Chadron, and Arikaree Formations are not significant aquifers in the La Grange area (Borchert 1976). Transmissive units that form aquifers in the vicinity of LaGrange are the alluvium and the Brule Formation of the White River Group.\
\
The alluvium consists of valley-fill deposits in the vicinity of La Grange and floodplain deposits extending along most of Horse Creek and its principal tributary, Bear Creek. The alluvium is saturated and permeable in the lowlands near Horse Creek, and is hydraulically connected with most of the underlying White River Group. Transmissivity estimates for the alluvium provided in Borchert (1976) range from 17200 ft2/d to 50,200 ft2/d with a mean of 33,150 ft2/d.\
\
The Brule Formation is the uppermost formation of the White River Group and underlies the alluvium in the valley of Horse Creek. The Brulé formation consists of relatively uniform moderately well-consolidated silt and very fine grained sand and massive, moderately hard, brittle, argillaceous siltstone. It is generally considered an aquitard, but may exhibit fracturing and secondary permeability in certain areas, resulting in significant local water production. Both the Sherard No 6 well and the Bill Ward No. 2 well produce water from alluvium. The Bill Ward No. 2 Well is 60 feet deep and the geologic log of the well makes no mention of the Brule Formation or other hard/impermeable material, so it may be possible to deepen the well slightly in alluvial material. However, the alluvium is generally understood to be approximately 60 feet thick in most of this area. The Sherard No. 6 well is 43 feet deep and the geologic log of the location notes clay/hardpan at 36 feet, which suggests the top of the Brule Formation. It may be possible to produce additional water at either location by deepening the well and attempting to access fracture permeability in the Brule Formation. However, this could also be unsuccessful if attempted, at considerable expense.\
\
The Sherard No. 6 and Bill Ward No. 2 wells are in an area for which the numerical model constructed by Hinckley Consulting and AMEC (2011) used 89.14 ft/d as the hydraulic conductivity value. As this model was constructed and parameterized using available pumping test and water level data from all wells in the surrounding area, this value is considered the best available estimate of hydraulic conductivity at the location of the wells. It is possible that local production test data would yield a different hydraulic conductivity value, however.\
\
In the area east of Horse Creek, Hawk Springs Reservoir and 14 adjacent wells used to supplement surface-water supply in the reservoir are in a natural discharge area. The area upgradient of the reservoir contains over 30 irrigation wells. In this area, declining water levels have caused concern about the effects of well pumping on the hydrologic system for decades. Numerical modeling by Borchert (1985) and Hinckley Consulting and AMEC (2011) was conducted to evaluate the connection between groundwater and surface water resources and determine the sustainable rate of groundwater production. The First Amended Order of the State Engineer - Horse Creek Basin was issued based on the results of the Hinckley Consulting and AMEC (2011) modeling.\

{{< pagebreak >}}

# Horse Creek Order

The Horse Creek Order is an order issued by the Wyoming State Engineer ("The Order"). The Order was first issued on July 19, 2013, and an ammended order was issued May 31, 2017. The Order was issued for the LaGrange Aquifer and surface water diversions from Horse Creek at and below the Brown and LaGrange diversion in southern Goshen County, Wyoming. The wells subject to this interference complaint, Sherard No. 6 and Bill Ward No. 2, are located in the area affected by the Horse Creek Order. The wells are completed in the LaGrange Aquifer.\
\
The Horse Creek Order was issued in response to concerns over increasing conflicts between surface water and groundwater resources, which are detailed in a technical study of the project area (Hinckley Consulting and AMEC 2011). The Order closed the LaGrange Aquifer to further permitting of large capacity wells, and required the adjudication of previously unadjudicated groundwater permits. Also, groundwater used for irrigation from the LaGrange Aquifer was limited to 12 inches per year for the three year subsequent to 2014, and a total of 36 inches over that period. Some flexibility within the 3-year period was allowed. All groundwater wells permitted for over 25 gallons per minute were required to have flow meters installed, and annual use reporting was required. These limitations to groundwater use were placed in lieu of calls for regulation from surface water rights.\
\
Surface water diversions, and reservoirs, were required to have acceptable control and measurement capabilities. Those diversions seeking to divert water during the winter were required to have acceptable control and measurement capabilities prior to diverting in the winter of 2013-2014, and any such diversions were required to be spread across the appropriate permitted (or adjudicated) acres up to the soil holding capacity only.\
\
The Order has been reassessed periodically since its issuance. The 2017 ammended order increased the groundwater production cap from 12 acre-in per year to 15 acre in per year, with a three year rolling cap of 45 acre in per year.\
\
Both wells subject of this interference complaint have production caps associated with the Horse Creek Order and meter/reporting requirements to report production data to the SEO. This information is compiled annually in the SEO Hydrographer Reports for Division I. A compilation of this information is provided in Table 2. According to Table 2, both water rights generally pump an amount of water well below their allotted annual production cap. In the case of Sherard No. 6, the lack of pumping is an attempt to preserve the water level in the adjacent gravel pit (Gabriel Ruiz, personal communication, 8/18/2022).\

{{< pagebreak >}}

# Data and Analysis

This section contains data relating to groundwater levels, groundwater production rates, and estimated cones of depression for the wells under consideration, which was compiled by the SEO- Ground Water Division.\

## Groundwater Level Data

Information on pump flow rates and water levels from the statements of completion of the wells under consideration is summarized in Table 1. Apart from the information on the statement of completion, there are no available water level records for either well. The SEO monitors groundwater levels at several monitoring wells located within a few miles of this location. The nearest monitoring wells are J. Ward, located about 0.75 miles west of the gravel pit, Ward's Yard about 1.25 miles west of the gravel pit, and LaGrange No. 1, located about 2 miles southeast of the gravel pit. Hydrographs for these three wells for the time period 2010-2022 are included in Appendix C. Appendix C also contains a location map of all monitoring wells in the area and hydrographs from each monitoring location for the entire period of record.\

Water levels at each location have declined somewhat since 2016, corresponding to a generally drier period. Relative to historical water levels recorded since approximately 1980, current water levels at Ward's Yard are approximately the same, J. Ward is about 10 feet below it's historical mean water level, and LaGrange No. 1 is about 7 feet below it's 1980-2000 water level, which is comparable to levels observed at that location during the early 2000s.\

During a site visit on 8/29/2022, SEO personnel estimated that the water level in the pit was 9.62 feet below full pool, which is approximately 20.62 feet below the ground elevation at the location of Sherard No. 6. According to observations by Gabe Ruiz, the Bill Ward No. 2 well had been in operation for 66 of the preceding 90 days as of 8/29/2022.

## Groundwater Production Data

Production meter readings collected by SEO personnel were used to tabulate total annual water production for each well to assess compliance with the Horse Creek Order. This information is released in annual hydrographer reports for Water Division 1, District 2. Table 2 contains the compiled annual production reported from Bill Ward No. 2 and Sherard No. 6. Complete tables from the annual hydrographer reports are provided in Appendix D. The data shows that the average annual production from Bill Ward No. 2 from 2017 to 2021 was 94.71 acre-feet per year. This would correspond to pumping approximately 226 gallons per minute continuously during a 95 day irrigation season. Sherard No. 6 shows no production since 2018. During 2017 and 2018, when the well was pumped, the average annual production from Sherard No. 6 was 8.2 acre-feet per year. This would correspond to pumping approximately 20 gallons per minute continuously during a 95 day irrigation season. Both of these pumping rates are a small fraction of the permitted appropriation amount associated with each water right (approximately 10% of the appropriation amount for Bill Ward No. 2 and 1% of the appropriation amount for Sherard No. 6). Both the Gross Wilkinson Ranch and Gabriel Ruiz are and have been in compliance with the Horse Creek Order in terms of their overall rate of irrigation application.\

On average for the years 2017-2021, the Gross Wilkinson ranch applied 2445 acre inches per year for irrigation, 46.5% of which comes from Bill Ward No. 2. Assuming a year round average water surface area of 7 acres, and applying the evaporation rate estimated by Curtis and Grimes (2004), the evaporative loss from the gravel pit is estimated to be about 243.6 acre inches per year.

## Estimated Theroetical Cones of Depression

The Theis equation (Theis 1935) was used to project drawdown from pumping each well at 60% of it's maximum adjudicated flow rate continuously during a 95 day irrigation season. The cone of depression for each well is plotted and superimposed on the other well's on Figure 2. Because drawdown is additive, the drawdown at a location in the area of overlapping cones of depression between the two wells would be equal to the sum of the predicted drawdowns for each well individually (Fetter, 1994).\

One of the assumptions underlying the Theis Equation is that the aquifer is of infinite extent (Theis, 1935). This is generally not an issue when analyzing a short term pumping test using the Theis equation, but it is important to recognize that this condition is not met when making projections of theoretical drawdown at regional scale over very long periods of time. In our application, we use the Theis equation to project maximum drawdown at the end of a single 95 day irrigation season.

Figure 3 depicts a similar estimate of drawdown using the Theis equation, except that the average annual use rate is used in setting the flow rate from the well. This figure suggests a much smaller radius of influence for Sherard No. 6, because of the lack of groundwater pumping.

Figure 4 depicts the Sherard No 6 Well's cone of depression based on 60% of it's permitted maximum flow rate, and the Bill Ward No. 2 well based on 2017-2021 average annual use rate. The overlap in the cones of depression depicted on Figure 4 is approximately 20%.

These calculations suggest there is potential for Bill Ward No. 2 to interfere significantly with Sherard No. 6 depending on the extraction flow rate at each location. However, Figure 3 suggests it is possible for Sherard No. 6 to extract water at its permitted flow rate without "unreasonable" interference from Bill Ward No. 2 at production levels comparable to current annual use from Bill Ward No. 2. If both wells were pumped as suggested in Figure 3, the water level in the adjacent Gravel Pit would likely be affected. However, the Sherard No. 6 water right does not guarantee any specific water level in the pit. The water right simply permits the pit as a point of use.

{{< pagebreak >}}

# Options

The Ground Water Division has identified potential solutions for ameliorating the impacts which were likely experienced at the Sherard No. 6 well. These solutions are presented in no particular order.\

## No Regulation

The Horse Creek Order specifies that the alluvial aquifer of Horse Creek and the regional streams are one source of supply. The Horse Creek Order conservation measures were specifically intended to the prevent priority regulation of groundwater wells. Adopting priority regulation of a subset of groundwater wells in the context of this interference complaint circumvents the Horse Creek Order, is inconsistent with the Horse Creek Order, and is contrary to the principles of Wyoming Water Law in that the principle of first in time, first in right, would be applied selectively, rather than equally, across all the appropriators of the single source of supply.\

## Require use of water by Sherard No. 6 before interference can be claimed

SEO records indicate that no water has been produced by the Sherard No. 6 well since 2018. Beneficial use is the basis, measure, and the limit of all water rights. The Sherard No. 6 water right may be eligible for abandonment under Wyo. Stat. 41-3-401. The instantaneous flow rate observed on the 8/29/2022 site visit from the Sherard No. 6 well was 200 GPM, which is 1/10th of the adjudicated maximum flow rate for this well. The flow rate observed was likely less than the adjudicated maximum flow rate due to ongoing drought, low water levels generally, and to an extent, due to interference from pumping Bill Ward No. 2. However, claiming interference seems inappropriate given that a relatively abundant supply of water (200 GPM) is readily available by pumping Sherard No. 6.\

## Furnishment of water at the expense of the junior appropriator

If it can be shown that the Sherard No. 6 Well cannot yield an adequate supply of water for the permitted uses associated with the water right (irrigation, miscellaneous) during the irrigation season by active pumping, the provision of water to the owner of the Sherard No. 6 Well at the specified point of use (i.e., Gravel Pit in NWSW of Sec 33, T20N, R61W) by owner of the Bill Ward No. 2 well, would seem to be appropriate, consistent with Wyo. Stat. 41-3-911(a), although it should be noted this section pertains only to interference with domestic or stock wells specifically. This would function to supply the Sherard No. 6 water right. This would not function to maintain any specific water level in the gravel pit. Per Wyo. Stat. 41-3-933, the water level or pressure at the appropriator's point of division is not maintained any level higher than that required for maximum beneficial use of the water in the source of supply. The Sherard No. 6 water right has no claim to this water on the basis of use specifically. The Sherard No. 6 water right specifies that miscellaneous use (Fish culture and recreational purposes) is a valid beneficial use of the water. Beneficial use is the basis, measure, and the limit of all water rights. If water is not beneficially applied for fish culture, recreational purposes, or irrigation purposes, the owner of Sherard No. 6 is legally obligated to forgo the water right and allow the water to be put to beneficial use by junior appropriators, i.e. the owner of Bill Ward No. 2.\

## Curtailment of production from Bill Ward No. 2 to a "reasonable" level of interference

SEO records suggest that average annual water production from Bill Ward No. 2 Well during the last 5 years (2017-2021) was 94.71 acre-feet per year. Our calculations of the cones of depression caused by pumping Sherard No. 6 and Bill Ward No. 2 suggest that there would be a 20% overlap of the cones of depression if each well was operated for 95 days, with Sherard No. 6 pumping 1200 GPM and Bill Ward No. 2 pumping 226 GPM. Limiting the production rate for Bill Ward No. 2 to 226 GPM could reduce the magnitude of interference with Sherard No. 6 to a "reasonable" level, consistent with the use of the language "unreasonable interference" in Wyo. Stat. 41-3-911(a) while allowing continued operation of Bill Ward No. 2 to support irrigation use. Again, the statement about "unreasonable interference" occurs in reference to interference with domestic and stock wells specifically.\

## User Agreement

Wyo. Stat. §41-3-915(c) specifies that appropriators within a Control Area "may agree to any method or scheme of control of withdrawals, well spacing, apportionment, rotation or proration of the common supply of underground water." The State Engineer encourages and promotes such agreements. Although the subject area is not a Control Area, it is analogous given its regulated status under the Horse Creek Order. A User Agreement might provide a mechanism for implementing one of options described above. A voluntary user agreement may be the most effective way to ration the available water resources. The original property owners acknowledged this in stating in the remarks section of Permit No. U.W. 8539 that there was an agreement between the property owners (at the time) that Permit No. U.W. 5461 (Sherard No. 6) would have first right to use of the water. The presence of that user agreement, however, does not diminish the validity of the Bill Ward No. 2 water right. It is suggested that SEO personnel work with the property owners to develop or revise a user agreement. Personal communication with Gabriel Ruiz (8/18/2022 and 8/29/2022) suggests that there was a recent user agreement in place between the two property owners, but that Mr. Ruiz believes the other property owner is not following that agreement. This should be revisited in discussions with the property owners.\

## Rotation

Wyoming Statute § 41-3-612 provides for rotation of water. A written notice of intention to rotate must be submitted to the hydrographer-commissioner and may involve various appropriations owned by one party, or multiple appropriations owned by different parties. The hydrographer-commissioner exercises broad authority over authorizing and regulating proposals to rotate. A simple rotation scheme of pumping Bill Ward No. 2 10 days on / 10 days off throughout the irrigation season may minimize the cumulative drawdown on the aquifer and gravel pit, allowing time for the aquifer to recharge the water level in the pit during dry periods and preventing excessive dewatering of the pit that negatively affects fish culture. The hydrographer-commissioner may work with the appropriators in developing an acceptable rotation scheme.\

## Regulation of Bill Ward No. 2

Withdrawals of water from Bill Ward No. 2 could be stopped, to protect the senior water right of Sherard No. 6. This option is not preferred because of existing measures to conserve water and prevent priority regulation of groundwater wells in this area (Horse Creek Order). It is also possible that other wells contribute to the interference with Sherard No. 6, and it is possible that nearby junior appropriator wells interfere with Bill Ward No. 2. Invoking this regulation mechanism could potentially trigger a cascade of interference complaints that would expand outward to the point that most or all users of the single source of supply would become involved. This could result in priority regulation of all groundwater wells in the LaGrange Aquifer in a single schedule of priorities (Wyo. Stat. 41-3-916) in combination with surface water, which would result in the curtailment of groundwater use generally in favor of senior surface water rights.\

{{< pagebreak >}}

# Conclusions and Recommendations

..

{{< pagebreak >}}

# References

Borchert, W.B. 1976. "Geohydrology of the Albin and La Grange Areas, Southeastern Wyoming." Report 76--118. Water-Resources Investigations Report. USGS Publications Warehouse. https://doi.org/10.3133/wri76118.

Borchert, W.B. 1985. "The Ground-Water System in the LaGrange Aquifer near LaGrange, Southeastern Wyoming." Report 83--4024. Water-Resources Investigations Report. USGS Publications Warehouse. https://doi.org/10.3133/wri834024.

Fetter, C.W. 2001. Applied Hydrogeology. Fourth. Upper Saddle River, New Jersey: Prentice-Hall. Hinckley Consulting, and AMEC. 2011. "Horse Creek Groundwater / Surface Water Connection Investigation, Goshen and Laramie Counties, Wyoming." https://drive.google.com/file/d/1xkTe4ErjcTf2b3o90BhB2hw3cK6JeFHx/view. J. Curtis and K. Grimes. 2004. Wyoming Climate Atlas. Water Resources Data System and State Climate Office. "NOAA U.S. Climate Normals 1991-2020." n.d. Accessed August 26, 2022. https://registry.opendata.aws/noaa-climate-normals.

Rapp, J. R., F. N. Visher, R. T. Littleton, and W. H. Durum. 1957. "Geology and Ground-Water Resources of Goshen County Wyoming with a Section on Chemical Quality of the Ground Water." Report 1377. Water Supply Paper. USGS Publications Warehouse. https://doi.org/10.3133/wsp1377.

Stafford, J.E., and A.M. Loveland. 2020. "Preliminary Geologic Map of the Chugwater 30' x 60' Quadrangle, Goshen, Platte, and Laramie Counties, Wyoming, and Scotts Bluff and Banner Counties, Nebraska." Wyoming State Geological Survey Open File Report 20--1. https://sales.wsgs.wyo.gov/preliminary-geologic-map-of-the-chugwater-30-x-60-quadrangle-goshen-platte-and-laramie-counties-wyoming-and-scotts-bluff-and-banner-counties-nebraska-2020/.

Theis, C.V. 1935. "The Relation between the Lowering of the Piezometric Surface and the Rate and Duration of Discharge of a Well Using Groundwater Storage." Transactions of the American Geophysical Union 16: 519--24.

Wyoming State Engineer's Office. 2017. "First Amended Order of the State Engineer - Horse Creek Basin." https://drive.google.com/file/d/1GzYh5WPjrrYOques1o_7pANlxfJjTEF7/view.
